[[entries]]
id = "08afae87-acec-4c9c-ae97-e218cb53c891"
type = "breaking change"
description = "Update `Params()` constructor to accept multiple arguments, making the construction of such objects more readable in code."
author = "@NiklasRosenstein"
