[[entries]]
id = "08afae87-acec-4c9c-ae97-e218cb53c891"
type = "breaking change"
description = "Update `Params()` constructor to accept multiple arguments, making the construction of such objects more readable in code."
author = "@NiklasRosenstein"

[[entries]]
id = "b34ceac4-05f5-4333-82d9-9a7c718d02ae"
type = "breaking change"
description = "Update `RulesEngine` API and add support for union memberships."
author = "@NiklasRosenstein"

[[entries]]
id = "3b1fb663-dc49-4886-98c2-1928ae012ec3"
type = "breaking change"
description = "rename `RulesGraph` to `RuleGraph` and `RulesEngine` to `RuleEngine`"
author = "@NiklasRosenstein"

[[entries]]
id = "994688bb-fbae-4f41-9b45-e1066bcaa524"
type = "breaking change"
description = "Rework `RuleEngine` and `RuleGraph` API, rename `Rule` to `ProductionRule`, add `UnionRule`, require that the `@rule()` decorator is called"
author = "@NiklasRosenstein"
