[[entries]]
id = "77cde700-421e-4a16-afab-196f15d53b57"
type = "feature"
description = "Add `RulesGraph.update()`"
author = "@NiklasRosenstein"

[[entries]]
id = "b97304c1-9bed-4799-af6a-cc84b6cce142"
type = "feature"
description = "add `RulesEngine.add_rules()`"
author = "@NiklasRosenstein"
