name: "Examples"

on:
  push: { branches: [ "develop" ], tags: [ "*" ] }
  pull_request: { branches: [ "develop" ] }

jobs:

  example-codegen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: python-slap/slap-cli@gha/install/v1
    - run: slap install -vv --no-venv-check
    - run: python examples/codegen/main.py

  example-hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: python-slap/slap-cli@gha/install/v1
    - run: slap install -vv --no-venv-check
    - run: python examples/hello.py | grep "Hello World!"

  readme-up-to-date-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: python-slap/slap-cli@gha/install/v1
    - run: slap install -vv --no-venv-check
    - run: python -m adjudicator.examples.readmesync
    - run: git diff --exit-code README.md
